### ISSUE TITLE
Add better support for slugs?

### ISSUE THREAD

**Issue by subhendukundu** [frandiox/vitedge#17]
To make the slug work this is what I have done so far.
Added
`const pages = import.meta.glob('./pages/**/*.jsx')` in [routes.js](https://github.com/subhendukundu/cool-bio-analytics/blob/main/src/routes.js#L5)

Then added a filename as [src/pages/projects/:name.jsx](https://github.com/subhendukundu/cool-bio-analytics/blob/main/src/pages/projects/:name.jsx)

This is working. What would be the best practice to do this?
With this approach, if I need to add a `not-found` page something like [this](https://github.com/frandiox/vitessedge-template/blob/f3b34d2d297f64f4713ebb1d7a9c51ffa96da4f3/src/pages/%5B...all%5D.vue), then I have to add the page like `src/pages/projects/*.jsx`. What do you think?

**Comment by frandiox** [comment]
The filesystem routing would ideally be implemented in a separate plugin: https://github.com/hannoeru/vite-plugin-pages/issues/11
That one works for Vue and I think supporting React shouldn't be too hard.

In the mean time, I think what you've done sounds good. Make sure you choose filenames that are not troublesome in Linux, Mac, and Windows. In the import logic you can replace characters to whatever the router expects -- .e.g transforming file `deep/path/[name].js` to route `deep/path/:name`.

```js
path.replace(/\[(\w+)\]/g, (_, s1) => `:${s1}`)
```

Same for the not found, I guess you can use something like `[catchAll].js` for example and then add some logic in `routes.js` for changing it to whatever React router understands (`/*`, I think?).

**Comment by subhendukundu** [comment]
So this is what I have added to `routes.js`
```
import React from 'react'

// Auto generates routes from files under ./pages
// https://vitejs.dev/guide/features.html#glob-import
const pages = import.meta.glob('./pages/**/*.jsx')

// Follow `react-router-config` route structure
export const routes = Object.keys(pages).map((path) => {
  const name = path.match(/\.\/pages\/(.*)\.jsx$/)[1]
  let component = null
  console.log(name)

  return {
    name: name.toLowerCase(),
    path: name === 'Home' ? '/' : `/${name.replace(/\[(\w+)\]/g, (_, s1) => `:${s1}`).toLowerCase()}`,
    // Async pages
    component (props) {
      if (!component) {
        const loadingComponent = pages[path]().then((result) => {
          component = result.default
        })

        // Suspense will re-render when component is ready
        throw loadingComponent
      }

      return React.createElement(component, props)
    }
  }
})

```
While my folder name is `[name].jsx`. This works too.
But when I do `history.push(/somename)`
I get this error
```
CustomError: ERR_MODULE_NOT_FOUND /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/functions/props/projects/[name].js /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/vitedge/dev/middleware.js module
    at finalizeResolution (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:360:11)
    at moduleResolve (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:809:10)
    at Object.defaultResolve (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:920:11)
    at /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/src/esm.ts:55:38
    at Generator.next (<anonymous>)
    at /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist/esm.js:4:12)
    at resolve (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist/esm.js:31:16)
    at resolve (file:///Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/vitedge/dev/ts-loader.js:6:26)
CustomError: ERR_MODULE_NOT_FOUND /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/functions/props/projects/[name].js /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/vitedge/dev/middleware.js module
    at finalizeResolution (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:360:11)
    at moduleResolve (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:809:10)
    at Object.defaultResolve (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:920:11)
    at /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/src/esm.ts:55:38
    at Generator.next (<anonymous>)
    at /Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist/esm.js:4:12)
    at resolve (/Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/ts-node/dist/esm.js:31:16)
    at resolve (file:///Users/subkundu/Desktop/Projects/Higgle/cool.bio/cool-bio-analytics-worker-react/node_modules/vitedge/dev/ts-loader.js:6:26)
```
But when I hard refresh the page, the error doesn't show up. only with routing it shows up.

**Comment by frandiox** [comment]
That's weird, looks like React router is choking on something. Does it happen with every route or only those that have parameters?

The SSR build bundles all the routes so it's only in SPA mode when it uses dynamic imports.

**Comment by frandiox** [comment]
So [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) supports React already. We can use that together with Vitedge 👍
