### ISSUE TITLE
First load for the simple Hello world sample is about 1,59MB  

### ISSUE THREAD

**Issue by lakano** [frandiox/vitedge#26]
Hello,

I don't known if this is expected, but just following the documentation sample for the Hello World + counter, and  on the first load there is 1,59MB to download, it's a lot for a so small part of code, and impact SEO performances. 

Do you known what cause theses files sizes ?
![Photo of assets files sizes](https://user-images.githubusercontent.com/731955/116313754-755b5500-a7ae-11eb-9f6b-dfd9eb33e68b.png)

**Comment by frandiox** [comment]
That's indeed a lot. Is it during development or production? Can you link to the example you are using?

It should be more like the following examples:

- https://vitessedge.zable.workers.dev/
- https://vitedge-vue.zable.workers.dev/

**Comment by lakano** [comment]
It's during development with SSR mode, but I've not tried to upload it. 
I've pushed my code here: https://github.com/lakano/cf-tests

I'll test to deploy it, it's may be better in production, but there is a way to see/simulate exactly the same content/sizes than it will be in production ?  ( some kind of --production flag )

**Comment by frandiox** [comment]
@lakano Ah no, there's no development mode to simulate production because the magic of Vite is precisely that, it skips bundling during dev to speed it up.

It would be possible to have some kind of build watch and refresh outside Vite, and I'd like to combine this with Wrangler so it directly runs development in a CF worker. But that needs to wait until https://github.com/frandiox/vitedge/pull/22 is finished.

**Comment by lakano** [comment]
Ok. About wrangler, what's the good way to use it with vitedge please?
I've tried a "vitedge build", then updated my package.json to add "main: dist/ssr/main.js" but after a "wranger dev" I have theses kind of errors:
```
wrangler dev                                                                                                                                                                 6.7s  mer. 28 avril 2021 07:50:42
👀  ./node_modules/@vueuse/head/dist/index.mjs 316:11-26
Can't import the named export 'defineComponent' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
./node_modules/@vueuse/head/dist/index.mjs 69:15-21
Can't import the named export 'inject' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
./node_modules/@vueuse/head/dist/index.mjs 237:4-19
Can't import the named export 'onBeforeUnmount' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
./node_modules/@vueuse/head/dist/index.mjs 321:4-19
Can't import the named export 'onBeforeUnmount' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
./node_modules/@vueuse/head/dist/index.mjs 230:18-21
Can't import the named export 'ref' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
./node_modules/@vueuse/head/dist/index.mjs 334:14-17
Can't import the named export 'ref' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
./node_modules/@vueuse/head/dist/index.mjs 234:4-15
Can't import the named export 'watchEffect' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
./node_modules/@vueuse/head/dist/index.mjs 328:6-17
Can't import the named export 'watchEffect' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1369:22)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1168:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1163:28)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compiler.js:622:17
    at eval (eval at create (/home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1095:12
    at /home/guillaume/.cache/.wrangler/wranglerjs-1.16.1/node_modules/webpack/lib/Compilation.js:1007:9
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
 @ ./dist/ssr/main.js
Error: webpack returned an error. You may be able to resolve this issue by running npm install.

```

**Comment by lakano** [comment]
( oups! may be you prefer I move my last question in an separate issue ? )

**Comment by lakano** [comment]
( I'll create another issue ticket about my 2nd problem with Wrangler ) 

About the file size, I'll try to upload it to compare, but after a "vitedge build", do we need to add some packages in the dist/ssr/package.json and to run a "npm install" ?

**Comment by frandiox** [comment]
@lakano No, adding dependencies to the dist files shouldn't be necessary if your project folder structure is similar to the starter template.

Right now, Vite is not bundling all the dependencies for the SSR build because it is meant to be for Node environment (more info [here](https://vitejs.dev/guide/ssr.html#ssr-externals)).
However, CF worker needs everything bundled. That's where Wrangler's Webpack build helps. However, for this to work your `worker-site` and `dist` folder should be direct children of the folder that has your `node_modules`.
Therefore, even though `vitedge build` is not bundling all the deps (due to Vite's behavior), `wrangler dev` or `wrangler publish` should do the rest.

Again, this should all be simpler once [custom builds](https://github.com/frandiox/vitedge/pull/22) are available since it will be able to bundle everything without using Webpack.

**Comment by frandiox** [comment]
@lakano Did you have time to test this in prod?
